<?php

/**
 * @file drupal_ckeditor_paste_striptags.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_ckeditor_settings_alter().
 */
function drupal_ckeditor_paste_striptags_ckeditor_settings_alter(&$settings, $conf) {
  // Change the ckeditor config path.
  $settings['customConfig'] = base_path() . drupal_get_path('module', 'drupal_ckeditor_paste_striptags') . '/drupal_ckeditor_paste_striptags.ckeditor.config.js';
}
